FROM postgres:16

ARG UID=1000
ARG GID=1000

RUN groupmod -g "${GID}" postgres \
    && usermod -u "${UID}" -g "${GID}" postgres \
    && mkdir -p /var/lib/postgresql/data \
    && chown -R postgres:postgres /var/lib/postgresql

USER postgres
