FROM python:3.10-slim

WORKDIR /app

COPY deploy/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src

EXPOSE 8080

ENV PYTHONPATH=/app

CMD ["uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "8080"]
